### ISSUE TITLE
Timespan is removed completely

### ISSUE THREAD

**Issue by PenguinJunk** [SecurityEssentials/vttprocessor#24]
I am very new to NVIVO and your helpful tool, so please forgive me if this is user error.

When I use your tool on my Team-generated docx file (which contains timespans, speakers and content) it creates a tab-delimited file of the format:

`<speaker>\t\t<content>`

I've tried poking around in the tool and file and can maybe bodge an importable file (although import doesn't like the fact i have no timespan). Is this due to a recent update in Teams transcription?

Attached is a mwe Teams transcription and the resulting NVivo txt

[interviewmwe_2024-07-05.docx](https://github.com/user-attachments/files/16111609/interviewmwe_2024-07-05.docx)

[interviewmwe_2024-07-05.txt](https://github.com/user-attachments/files/16111592/interviewmwe_2024-07-05.txt)

**Comment by PenguinJunk** [comment]
with experience, I've managed to overcome this - my problem was that I was editing (anonymising) the speaker label before conversion - I guess removing some vital spacing. If I do this after conversion it works really well.

**Comment by charlesweir** [comment]
Not an error.
